apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  template:
    metadata:
      labels:
        app: myapi
        service: api
    spec:
      containers:
        - name: api
          image: ishippwcacr.azurecr.io/api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: myapi
    service: api
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: api